import sqlite3

# Lista de países en español y francés (alineados por posición)
paises = [
    ("Afganistán", "Afghanistan"),
    ("Albania", "Albanie"),
    ("Argelia", "Algérie"),
    ("Andorra", "Andorre"),
    ("Angola", "Angola"),
    ("Antigua y Barbuda", "Antigua-et-Barbuda"),
    ("Argentina", "Argentine"),
    ("Armenia", "Arménie"),
    ("Australia", "Australie"),
    ("Austria", "Autriche"),
    ("Azerbaiyán", "Azerbaïdjan"),
    ("Bahamas", "Bahamas"),
    ("Baréin", "Bahreïn"),
    ("Bangladés", "Bangladesh"),
    ("Barbados", "Barbade"),
    ("Bielorrusia", "Biélorussie"),
    ("Bélgica", "Belgique"),
    ("Belice", "Belize"),
    ("Benín", "Bénin"),
    ("Bután", "Bhoutan"),
    ("Bolivia", "Bolivie"),
    ("Bosnia y Herzegovina", "Bosnie-Herzégovine"),
    ("Botsuana", "Botswana"),
    ("Brasil", "Brésil"),
    ("Brunéi", "Brunei"),
    ("Bulgaria", "Bulgarie"),
    ("Burkina Faso", "Burkina Faso"),
    ("Burundi", "Burundi"),
    ("Cabo Verde", "Cap-Vert"),
    ("Camboya", "Cambodge"),
    ("Camerún", "Cameroun"),
    ("Canadá", "Canada"),
    ("República Centroafricana", "République centrafricaine"),
    ("Chad", "Tchad"),
    ("Chile", "Chili"),
    ("China", "Chine"),
    ("Colombia", "Colombie"),
    ("Comoras", "Comores"),
    ("Congo", "Congo"),
    ("Costa Rica", "Costa Rica"),
    ("Croacia", "Croatie"),
    ("Cuba", "Cuba"),
    ("Chipre", "Chypre"),
    ("República Checa", "République tchèque"),
    ("Dinamarca", "Danemark"),
    ("Yibuti", "Djibouti"),
    ("Dominica", "Dominique"),
    ("República Dominicana", "République dominicaine"),
    ("Ecuador", "Équateur"),
    ("Egipto", "Égypte"),
    ("El Salvador", "Salvador"),
    ("Guinea Ecuatorial", "Guinée équatoriale"),
    ("Eritrea", "Érythrée"),
    ("Estonia", "Estonie"),
    ("Esuatini", "Eswatini"),
    ("Etiopía", "Éthiopie"),
    ("Fiyi", "Fidji"),
    ("Finlandia", "Finlande"),
    ("Francia", "France"),
    ("Gabón", "Gabon"),
    ("Gambia", "Gambie"),
    ("Georgia", "Géorgie"),
    ("Alemania", "Allemagne"),
    ("Ghana", "Ghana"),
    ("Grecia", "Grèce"),
    ("Granada", "Grenade"),
    ("Guatemala", "Guatemala"),
    ("Guinea", "Guinée"),
    ("Guinea-Bisáu", "Guinée-Bissau"),
    ("Guyana", "Guyana"),
    ("Haití", "Haïti"),
    ("Honduras", "Honduras"),
    ("Hungría", "Hongrie"),
    ("Islandia", "Islande"),
    ("India", "Inde"),
    ("Indonesia", "Indonésie"),
    ("Irán", "Iran"),
    ("Irak", "Irak"),
    ("Irlanda", "Irlande"),
    ("Israel", "Israël"),
    ("Italia", "Italie"),
    ("Jamaica", "Jamaïque"),
    ("Japón", "Japon"),
    ("Jordania", "Jordanie"),
    ("Kazajistán", "Kazakhstan"),
    ("Kenia", "Kenya"),
    ("Kiribati", "Kiribati"),
    ("Corea del Norte", "Corée du Nord"),
    ("Corea del Sur", "Corée du Sud"),
    ("Kuwait", "Koweït"),
    ("Kirguistán", "Kirghizistan"),
    ("Laos", "Laos"),
    ("Letonia", "Lettonie"),
    ("Líbano", "Liban"),
    ("Lesoto", "Lesotho"),
    ("Liberia", "Libéria"),
    ("Libia", "Libye"),
    ("Liechtenstein", "Liechtenstein"),
    ("Lituania", "Lituanie"),
    ("Luxemburgo", "Luxembourg"),
    ("Madagascar", "Madagascar"),
    ("Malawi", "Malawi"),
    ("Malasia", "Malaisie"),
    ("Maldivas", "Maldives"),
    ("Malí", "Mali"),
    ("Malta", "Malte"),
    ("Islas Marshall", "Îles Marshall"),
    ("Mauritania", "Mauritanie"),
    ("Mauricio", "Maurice"),
    ("México", "Mexique"),
    ("Micronesia", "Micronésie"),
    ("Moldavia", "Moldavie"),
    ("Mónaco", "Monaco"),
    ("Mongolia", "Mongolie"),
    ("Montenegro", "Monténégro"),
    ("Marruecos", "Maroc"),
    ("Mozambique", "Mozambique"),
    ("Myanmar", "Myanmar"),
    ("Namibia", "Namibie"),
    ("Nauru", "Nauru"),
    ("Nepal", "Népal"),
    ("Países Bajos", "Pays-Bas"),
    ("Nueva Zelanda", "Nouvelle-Zélande"),
    ("Nicaragua", "Nicaragua"),
    ("Níger", "Niger"),
    ("Nigeria", "Nigéria"),
    ("Noruega", "Norvège"),
    ("Omán", "Oman"),
    ("Pakistán", "Pakistan"),
    ("Palau", "Palaos"),
    ("Panamá", "Panama"),
    ("Papúa Nueva Guinea", "Papouasie-Nouvelle-Guinée"),
    ("Paraguay", "Paraguay"),
    ("Perú", "Pérou"),
    ("Filipinas", "Philippines"),
    ("Polonia", "Pologne"),
    ("Portugal", "Portugal"),
    ("Catar", "Qatar"),
    ("Rumanía", "Roumanie"),
    ("Rusia", "Russie"),
    ("Ruanda", "Rwanda"),
    ("San Cristóbal y Nieves", "Saint-Christophe-et-Niévès"),
    ("Santa Lucía", "Sainte-Lucie"),
    ("San Vicente y las Granadinas", "Saint-Vincent-et-les-Grenadines"),
    ("Samoa", "Samoa"),
    ("San Marino", "Saint-Marin"),
    ("Santo Tomé y Príncipe", "Sao Tomé-et-Principe"),
    ("Arabia Saudita", "Arabie Saoudite"),
    ("Senegal", "Sénégal"),
    ("Serbia", "Serbie"),
    ("Seychelles", "Seychelles"),
    ("Sierra Leona", "Sierra Leone"),
    ("Singapur", "Singapour"),
    ("Eslovaquia", "Slovaquie"),
    ("Eslovenia", "Slovénie"),
    ("Islas Salomón", "Îles Salomon"),
    ("Somalia", "Somalie"),
    ("Sudáfrica", "Afrique du Sud"),
    ("Sudán del Sur", "Soudan du Sud"),
    ("España", "Espagne"),
    ("Sri Lanka", "Sri Lanka"),
    ("Sudán", "Soudan"),
    ("Surinam", "Suriname"),
    ("Suecia", "Suède"),
    ("Suiza", "Suisse"),
    ("Siria", "Syrie"),
    ("Tayikistán", "Tadjikistan"),
    ("Tanzania", "Tanzanie"),
    ("Tailandia", "Thaïlande"),
    ("Timor Oriental", "Timor oriental"),
    ("Togo", "Togo"),
    ("Tonga", "Tonga"),
    ("Trinidad y Tobago", "Trinité-et-Tobago"),
    ("Túnez", "Tunisie"),
    ("Turquía", "Turquie"),
    ("Turkmenistán", "Turkménistan"),
    ("Tuvalu", "Tuvalu"),
    ("Uganda", "Ouganda"),
    ("Ucrania", "Ukraine"),
    ("Emiratos Árabes Unidos", "Émirats arabes unis"),
    ("Reino Unido", "Royaume-Uni"),
    ("Estados Unidos", "États-Unis"),
    ("Uruguay", "Uruguay"),
    ("Uzbekistán", "Ouzbékistan"),
    ("Vanuatu", "Vanuatu"),
    ("Vaticano", "Vatican"),
    ("Venezuela", "Venezuela"),
    ("Vietnam", "Vietnam"),
    ("Yemen", "Yémen"),
    ("Zambia", "Zambie"),
    ("Zimbabue", "Zimbabwe"),
]

# Crear SQLite
DB_PATH = "paises_es_fr.sqlite"
TABLE_NAME = "paises"

conn = sqlite3.connect(DB_PATH)
cur = conn.cursor()

cur.execute(f"DROP TABLE IF EXISTS {TABLE_NAME}")
cur.execute(f"CREATE TABLE {TABLE_NAME} (pais_es TEXT, pais_fr TEXT)")

for es, fr in paises:
    cur.execute(f"INSERT INTO {TABLE_NAME} (pais_es, pais_fr) VALUES (?, ?)", (es, fr))

conn.commit()
conn.close()
print(f"SQLite generado: {DB_PATH} con {len(paises)} países")
