"""Initial migration

Revision ID: 8af07ea74430
Revises: 
Create Date: 2025-11-18 09:57:40.834963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8af07ea74430'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('allowed_groups', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('vat_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['business_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('villes')
    op.drop_table('clientes')
    op.drop_table('estadisticas_clientes_mes')
    op.drop_table('direcciones_alternativas')
    op.drop_table('historial_clientes')
    op.drop_table('deudas_clientes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deudas_clientes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), nullable=False),
    sa.Column('fecha_deuda', sa.DATE(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DATE(), nullable=False),
    sa.Column('documento', sa.VARCHAR(length=50), nullable=True),
    sa.Column('id_documento', sa.INTEGER(), nullable=True),
    sa.Column('tipo_documento', sa.VARCHAR(length=20), nullable=True),
    sa.Column('importe_total', sa.FLOAT(), nullable=False),
    sa.Column('importe_pagado', sa.FLOAT(), nullable=True),
    sa.Column('importe_pendiente', sa.FLOAT(), nullable=False),
    sa.Column('pagado', sa.BOOLEAN(), nullable=True),
    sa.Column('fecha_pago', sa.DATE(), nullable=True),
    sa.Column('observaciones', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_clientes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('tipo_operacion', sa.VARCHAR(length=50), nullable=True),
    sa.Column('documento', sa.VARCHAR(length=50), nullable=True),
    sa.Column('id_documento', sa.INTEGER(), nullable=True),
    sa.Column('importe', sa.FLOAT(), nullable=True),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('usuario', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direcciones_alternativas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=100), nullable=True),
    sa.Column('direccion1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('direccion2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('cp', sa.VARCHAR(length=10), nullable=True),
    sa.Column('poblacion', sa.VARCHAR(length=100), nullable=True),
    sa.Column('provincia', sa.VARCHAR(length=100), nullable=True),
    sa.Column('id_pais', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('comentarios', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estadisticas_clientes_mes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), nullable=False),
    sa.Column('anio', sa.INTEGER(), nullable=False),
    sa.Column('mes', sa.INTEGER(), nullable=False),
    sa.Column('importe_ventas', sa.FLOAT(), nullable=True),
    sa.Column('numero_operaciones', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_web', sa.INTEGER(), nullable=True),
    sa.Column('codigo_cliente', sa.VARCHAR(length=50), nullable=False),
    sa.Column('apellido1', sa.VARCHAR(length=100), nullable=True),
    sa.Column('apellido2', sa.VARCHAR(length=100), nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=True),
    sa.Column('nombre_fiscal', sa.VARCHAR(length=200), nullable=True),
    sa.Column('nombre_comercial', sa.VARCHAR(length=200), nullable=True),
    sa.Column('persona_contacto', sa.VARCHAR(length=200), nullable=True),
    sa.Column('cif_nif_siren', sa.VARCHAR(length=50), nullable=True),
    sa.Column('siret', sa.VARCHAR(length=14), nullable=True),
    sa.Column('cif_vies', sa.VARCHAR(length=50), nullable=True),
    sa.Column('direccion1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('direccion2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('cp', sa.VARCHAR(length=10), nullable=True),
    sa.Column('poblacion', sa.VARCHAR(length=100), nullable=True),
    sa.Column('provincia', sa.VARCHAR(length=100), nullable=True),
    sa.Column('id_pais', sa.INTEGER(), nullable=True),
    sa.Column('telefono1', sa.VARCHAR(length=50), nullable=True),
    sa.Column('telefono2', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fax', sa.VARCHAR(length=50), nullable=True),
    sa.Column('movil', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('web', sa.VARCHAR(length=200), nullable=True),
    sa.Column('fecha_alta', sa.DATE(), nullable=True),
    sa.Column('fecha_ultima_compra', sa.DATE(), nullable=True),
    sa.Column('fecha_nacimiento', sa.DATE(), nullable=True),
    sa.Column('acumulado_ventas', sa.FLOAT(), nullable=True),
    sa.Column('ventas_ejercicio', sa.FLOAT(), nullable=True),
    sa.Column('riesgo_maximo', sa.FLOAT(), nullable=True),
    sa.Column('deuda_actual', sa.FLOAT(), nullable=True),
    sa.Column('importe_pendiente', sa.FLOAT(), nullable=True),
    sa.Column('comentarios', sa.TEXT(), nullable=True),
    sa.Column('bloqueado', sa.BOOLEAN(), nullable=True),
    sa.Column('comentario_bloqueo', sa.TEXT(), nullable=True),
    sa.Column('observaciones', sa.VARCHAR(length=255), nullable=True),
    sa.Column('porc_dto_cliente', sa.FLOAT(), nullable=True),
    sa.Column('recargo_equivalencia', sa.BOOLEAN(), nullable=True),
    sa.Column('irpf', sa.BOOLEAN(), nullable=True),
    sa.Column('grupo_iva', sa.INTEGER(), nullable=True),
    sa.Column('cuenta_contable', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cuenta_iva_repercutido', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cuenta_deudas', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cuenta_cobros', sa.VARCHAR(length=50), nullable=True),
    sa.Column('id_forma_pago', sa.INTEGER(), nullable=True),
    sa.Column('dia_pago1', sa.INTEGER(), nullable=True),
    sa.Column('dia_pago2', sa.INTEGER(), nullable=True),
    sa.Column('entidad_bancaria', sa.VARCHAR(length=4), nullable=True),
    sa.Column('oficina_bancaria', sa.VARCHAR(length=4), nullable=True),
    sa.Column('dc', sa.VARCHAR(length=2), nullable=True),
    sa.Column('cuenta_corriente', sa.VARCHAR(length=10), nullable=True),
    sa.Column('importe_a_cuenta', sa.FLOAT(), nullable=True),
    sa.Column('vales', sa.FLOAT(), nullable=True),
    sa.Column('visa_distancia1', sa.VARCHAR(length=20), nullable=True),
    sa.Column('visa_distancia2', sa.VARCHAR(length=20), nullable=True),
    sa.Column('visa1_caduca_mes', sa.INTEGER(), nullable=True),
    sa.Column('visa2_caduca_mes', sa.INTEGER(), nullable=True),
    sa.Column('visa1_caduca_ano', sa.INTEGER(), nullable=True),
    sa.Column('visa2_caduca_ano', sa.INTEGER(), nullable=True),
    sa.Column('visa1_cod_valid', sa.INTEGER(), nullable=True),
    sa.Column('visa2_cod_valid', sa.INTEGER(), nullable=True),
    sa.Column('acceso_web', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password_web', sa.VARCHAR(length=100), nullable=True),
    sa.Column('id_tarifa', sa.INTEGER(), nullable=True),
    sa.Column('id_divisa', sa.INTEGER(), nullable=True),
    sa.Column('id_idioma_documentos', sa.INTEGER(), nullable=True),
    sa.Column('id_agente', sa.INTEGER(), nullable=True),
    sa.Column('id_transportista', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('villes',
    sa.Column('code_insee', sa.VARCHAR(length=10), nullable=False),
    sa.Column('code_postal', sa.VARCHAR(length=10), nullable=True),
    sa.Column('codes_postaux', sa.TEXT(), nullable=True),
    sa.Column('nom_standard', sa.VARCHAR(length=255), nullable=True),
    sa.Column('nom_standard_majuscule', sa.VARCHAR(length=255), nullable=True),
    sa.Column('reg_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('reg_nom', sa.VARCHAR(length=255), nullable=True),
    sa.Column('dep_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('dep_nom', sa.VARCHAR(length=255), nullable=True),
    sa.Column('canton_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('canton_nom', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('code_insee')
    )
    op.drop_table('companies')
    op.drop_table('users')
    op.drop_table('business_groups')
    # ### end Alembic commands ###
