"""add_sqlite_path_column

Revision ID: 928293cff6a2
Revises: 8a4be459f215
Create Date: 2025-11-27 04:13:14.546984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '928293cff6a2'
down_revision: Union[str, Sequence[str], None] = '8a4be459f215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_groups', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.add_column('empresas', sa.Column('ruta_base_datos_sqlite', sa.String(length=255), nullable=True, comment='Ruta relativa o absoluta a la BD SQLite'))
    op.alter_column('empresas', 'fecha_alta',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('empresas', 'fecha_modificacion',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('empresas', 'fecha_modificacion',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.alter_column('empresas', 'fecha_alta',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    op.drop_column('empresas', 'ruta_base_datos_sqlite')
    op.alter_column('business_groups', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=True)
    # ### end Alembic commands ###
