"""add_missing_company_fields

Revision ID: 8a4be459f215
Revises: 6accb119908d
Create Date: 2025-11-27 04:03:29.023908

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a4be459f215"
down_revision: Union[str, Sequence[str], None] = "6accb119908d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "business_groups",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=True,
    )
    op.add_column(
        "empresas",
        sa.Column("moneda_predeterminada", sa.String(length=10), nullable=True),
    )
    op.add_column(
        "empresas", sa.Column("actualizar_divisas", sa.Integer(), nullable=True)
    )
    op.add_column("empresas", sa.Column("aplicar_irpf", sa.Integer(), nullable=True))
    op.add_column("empresas", sa.Column("porcentaje_irpf", sa.Float(), nullable=True))
    op.add_column(
        "empresas", sa.Column("decimales_totales", sa.Integer(), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("decimales_precios", sa.Integer(), nullable=True)
    )
    op.add_column("empresas", sa.Column("digitos_factura", sa.Integer(), nullable=True))
    op.add_column(
        "empresas", sa.Column("serie_factura", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("dia_cierre_ejercicio", sa.Integer(), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("mes_cierre_ejercicio", sa.Integer(), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("enlace_web_activo", sa.Integer(), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("gestion_internacional", sa.Integer(), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("autocodificar_articulos", sa.Integer(), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("tamano_codigo_articulo", sa.Integer(), nullable=True)
    )
    op.add_column(
        "empresas",
        sa.Column("tarifa_predeterminada", sa.String(length=50), nullable=True),
    )
    op.add_column("empresas", sa.Column("margen_general", sa.Float(), nullable=True))
    op.add_column("empresas", sa.Column("margen_minimo", sa.Float(), nullable=True))
    op.add_column(
        "empresas", sa.Column("ruta_logo", sa.String(length=255), nullable=True)
    )
    op.add_column("empresas", sa.Column("comentario_albaran", sa.Text(), nullable=True))
    op.add_column("empresas", sa.Column("comentario_factura", sa.Text(), nullable=True))
    op.add_column(
        "empresas", sa.Column("horario_lunes", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("horario_martes", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("horario_miercoles", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("horario_jueves", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("horario_viernes", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("horario_sabado", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("horario_domingo", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "empresas",
        sa.Column("google_calendar_id", sa.String(length=255), nullable=True),
    )
    op.add_column("empresas", sa.Column("google_oauth_token", sa.Text(), nullable=True))
    op.add_column(
        "empresas", sa.Column("google_refresh_token", sa.Text(), nullable=True)
    )
    op.add_column(
        "empresas",
        sa.Column("google_token_expiry", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "empresas", sa.Column("activar_contabilidad", sa.Integer(), nullable=True)
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_venta_servicios", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_venta_mercaderias", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas", sa.Column("cuenta_acreedores", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("cuenta_proveedores", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("digitos_cuentas_contables", sa.Integer(), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("cuenta_clientes", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("cuenta_cobros", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("cuenta_pagos", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_iva_repercutido_1", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_iva_repercutido_2", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_iva_repercutido_3", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_iva_repercutido_4", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_iva_repercutido_re_1", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_iva_repercutido_re_2", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_iva_repercutido_re_3", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_iva_repercutido_re_4", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_iva_soportado_1", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_iva_soportado_2", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_iva_soportado_3", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_iva_soportado_4", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_iva_soportado_re_1", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_iva_soportado_re_2", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_iva_soportado_re_3", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas",
        sa.Column("cuenta_iva_soportado_re_4", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "empresas",
        sa.Column("inscripcion_registro", sa.String(length=200), nullable=True),
    )
    op.add_column(
        "empresas", sa.Column("ciudad_rcs", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("numero_rcs", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "empresas", sa.Column("numero_rm", sa.String(length=50), nullable=True)
    )
    op.add_column("empresas", sa.Column("siret", sa.String(length=50), nullable=True))
    op.add_column("empresas", sa.Column("ape_naf", sa.String(length=20), nullable=True))
    op.alter_column(
        "empresas",
        "group_id",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=None,
        nullable=False,
    )
    op.alter_column(
        "empresas",
        "id_pais",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "fecha_alta",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "activa",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "capital_social",
        existing_type=mysql.DECIMAL(precision=15, scale=2),
        server_default=None,
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "moneda_capital",
        existing_type=mysql.VARCHAR(length=3),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "regimen_iva",
        existing_type=mysql.VARCHAR(length=50),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "porcentaje_retencion",
        existing_type=mysql.DECIMAL(precision=5, scale=2),
        server_default=None,
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "exento_iva",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "intracomunitario",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "limite_credito",
        existing_type=mysql.DECIMAL(precision=15, scale=2),
        server_default=None,
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "dias_pago",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "descuento_general",
        existing_type=mysql.DECIMAL(precision=5, scale=2),
        server_default=None,
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "facturacion_anual",
        existing_type=mysql.DECIMAL(precision=15, scale=2),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "fecha_modificacion",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "motor_base_datos",
        existing_type=mysql.VARCHAR(length=20),
        server_default=None,
        existing_comment="Motor de base de datos: mariadb o postgresql",
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "host_mariadb",
        existing_type=mysql.VARCHAR(length=100),
        server_default=None,
        existing_comment="Host del servidor MariaDB",
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "puerto_mariadb",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=None,
        existing_comment="Puerto del servidor MariaDB",
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "usuario_mariadb",
        existing_type=mysql.VARCHAR(length=50),
        server_default=None,
        existing_comment="Usuario MariaDB",
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "password_mariadb",
        existing_type=mysql.VARCHAR(length=255),
        server_default=None,
        existing_comment="Contraseña MariaDB",
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "host_postgresql",
        existing_type=mysql.VARCHAR(length=100),
        server_default=None,
        existing_comment="Host del servidor PostgreSQL",
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "puerto_postgresql",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=None,
        existing_comment="Puerto del servidor PostgreSQL",
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "usuario_postgresql",
        existing_type=mysql.VARCHAR(length=50),
        server_default=None,
        existing_comment="Usuario PostgreSQL",
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "password_postgresql",
        existing_type=mysql.VARCHAR(length=255),
        server_default=None,
        existing_comment="Contraseña PostgreSQL",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "is_active",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "allowed_groups",
        existing_type=mysql.TEXT(),
        server_default=None,
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "allowed_groups",
        existing_type=mysql.TEXT(),
        server_default=sa.text("'[]'"),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("current_timestamp()"),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "is_active",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=sa.text("1"),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "password_postgresql",
        existing_type=mysql.VARCHAR(length=255),
        server_default=sa.text("'postgres'"),
        existing_comment="Contraseña PostgreSQL",
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "usuario_postgresql",
        existing_type=mysql.VARCHAR(length=50),
        server_default=sa.text("'postgres'"),
        existing_comment="Usuario PostgreSQL",
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "puerto_postgresql",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=sa.text("5432"),
        existing_comment="Puerto del servidor PostgreSQL",
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "host_postgresql",
        existing_type=mysql.VARCHAR(length=100),
        server_default=sa.text("'localhost'"),
        existing_comment="Host del servidor PostgreSQL",
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "password_mariadb",
        existing_type=mysql.VARCHAR(length=255),
        server_default=sa.text("'admin123'"),
        existing_comment="Contraseña MariaDB",
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "usuario_mariadb",
        existing_type=mysql.VARCHAR(length=50),
        server_default=sa.text("'admin'"),
        existing_comment="Usuario MariaDB",
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "puerto_mariadb",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=sa.text("3306"),
        existing_comment="Puerto del servidor MariaDB",
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "host_mariadb",
        existing_type=mysql.VARCHAR(length=100),
        server_default=sa.text("'localhost'"),
        existing_comment="Host del servidor MariaDB",
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "motor_base_datos",
        existing_type=mysql.VARCHAR(length=20),
        server_default=sa.text("'mariadb'"),
        existing_comment="Motor de base de datos: mariadb o postgresql",
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "fecha_modificacion",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("current_timestamp()"),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "facturacion_anual",
        existing_type=sa.Float(),
        type_=mysql.DECIMAL(precision=15, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "descuento_general",
        existing_type=sa.Float(),
        server_default=sa.text("0.00"),
        type_=mysql.DECIMAL(precision=5, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "dias_pago",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=sa.text("30"),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "limite_credito",
        existing_type=sa.Float(),
        server_default=sa.text("0.00"),
        type_=mysql.DECIMAL(precision=15, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "intracomunitario",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=sa.text("0"),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "exento_iva",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=sa.text("0"),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "porcentaje_retencion",
        existing_type=sa.Float(),
        server_default=sa.text("0.00"),
        type_=mysql.DECIMAL(precision=5, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "regimen_iva",
        existing_type=mysql.VARCHAR(length=50),
        server_default=sa.text("'General'"),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "moneda_capital",
        existing_type=mysql.VARCHAR(length=3),
        server_default=sa.text("'EUR'"),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "capital_social",
        existing_type=sa.Float(),
        server_default=sa.text("0.00"),
        type_=mysql.DECIMAL(precision=15, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "activa",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=sa.text("1"),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "fecha_alta",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("current_timestamp()"),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "id_pais",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=sa.text("1"),
        existing_nullable=True,
    )
    op.alter_column(
        "empresas",
        "group_id",
        existing_type=mysql.INTEGER(display_width=11),
        server_default=sa.text("1"),
        nullable=True,
    )
    op.drop_column("empresas", "ape_naf")
    op.drop_column("empresas", "siret")
    op.drop_column("empresas", "numero_rm")
    op.drop_column("empresas", "numero_rcs")
    op.drop_column("empresas", "ciudad_rcs")
    op.drop_column("empresas", "inscripcion_registro")
    op.drop_column("empresas", "cuenta_iva_soportado_re_4")
    op.drop_column("empresas", "cuenta_iva_soportado_re_3")
    op.drop_column("empresas", "cuenta_iva_soportado_re_2")
    op.drop_column("empresas", "cuenta_iva_soportado_re_1")
    op.drop_column("empresas", "cuenta_iva_soportado_4")
    op.drop_column("empresas", "cuenta_iva_soportado_3")
    op.drop_column("empresas", "cuenta_iva_soportado_2")
    op.drop_column("empresas", "cuenta_iva_soportado_1")
    op.drop_column("empresas", "cuenta_iva_repercutido_re_4")
    op.drop_column("empresas", "cuenta_iva_repercutido_re_3")
    op.drop_column("empresas", "cuenta_iva_repercutido_re_2")
    op.drop_column("empresas", "cuenta_iva_repercutido_re_1")
    op.drop_column("empresas", "cuenta_iva_repercutido_4")
    op.drop_column("empresas", "cuenta_iva_repercutido_3")
    op.drop_column("empresas", "cuenta_iva_repercutido_2")
    op.drop_column("empresas", "cuenta_iva_repercutido_1")
    op.drop_column("empresas", "cuenta_pagos")
    op.drop_column("empresas", "cuenta_cobros")
    op.drop_column("empresas", "cuenta_clientes")
    op.drop_column("empresas", "digitos_cuentas_contables")
    op.drop_column("empresas", "cuenta_proveedores")
    op.drop_column("empresas", "cuenta_acreedores")
    op.drop_column("empresas", "cuenta_venta_mercaderias")
    op.drop_column("empresas", "cuenta_venta_servicios")
    op.drop_column("empresas", "activar_contabilidad")
    op.drop_column("empresas", "google_token_expiry")
    op.drop_column("empresas", "google_refresh_token")
    op.drop_column("empresas", "google_oauth_token")
    op.drop_column("empresas", "google_calendar_id")
    op.drop_column("empresas", "horario_domingo")
    op.drop_column("empresas", "horario_sabado")
    op.drop_column("empresas", "horario_viernes")
    op.drop_column("empresas", "horario_jueves")
    op.drop_column("empresas", "horario_miercoles")
    op.drop_column("empresas", "horario_martes")
    op.drop_column("empresas", "horario_lunes")
    op.drop_column("empresas", "comentario_factura")
    op.drop_column("empresas", "comentario_albaran")
    op.drop_column("empresas", "ruta_logo")
    op.drop_column("empresas", "margen_minimo")
    op.drop_column("empresas", "margen_general")
    op.drop_column("empresas", "tarifa_predeterminada")
    op.drop_column("empresas", "tamano_codigo_articulo")
    op.drop_column("empresas", "autocodificar_articulos")
    op.drop_column("empresas", "gestion_internacional")
    op.drop_column("empresas", "enlace_web_activo")
    op.drop_column("empresas", "mes_cierre_ejercicio")
    op.drop_column("empresas", "dia_cierre_ejercicio")
    op.drop_column("empresas", "serie_factura")
    op.drop_column("empresas", "digitos_factura")
    op.drop_column("empresas", "decimales_precios")
    op.drop_column("empresas", "decimales_totales")
    op.drop_column("empresas", "porcentaje_irpf")
    op.drop_column("empresas", "aplicar_irpf")
    op.drop_column("empresas", "actualizar_divisas")
    op.drop_column("empresas", "moneda_predeterminada")
    op.alter_column(
        "business_groups",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("current_timestamp()"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
