# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDateEdit, QFrame, QGridLayout,
    QHBoxLayout, QLabel, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QSpacerItem,
    QStackedWidget, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1245, 487)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(0, 0))
        icon = QIcon()
        icon.addFile(u":/Icons/PNG/redfox.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QSize(36, 36))
        MainWindow.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QMainWindow.DockOption.AllowTabbedDocks|QMainWindow.DockOption.ForceTabbedDocks)
        self.btnClientes = QAction(MainWindow)
        self.btnClientes.setObjectName(u"btnClientes")
        icon1 = QIcon()
        icon1.addFile(u":/Icons/PNG/clientes.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon1.addFile(u":/Icons/PNG/clientes.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.btnClientes.setIcon(icon1)
        self.btnClientes.setIconVisibleInMenu(True)
        self.btnProveedores = QAction(MainWindow)
        self.btnProveedores.setObjectName(u"btnProveedores")
        icon2 = QIcon()
        icon2.addFile(u":/Icons/PNG/proveedores.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.btnProveedores.setIcon(icon2)
        self.btnProveedores.setIconVisibleInMenu(True)
        self.btnArt_culos = QAction(MainWindow)
        self.btnArt_culos.setObjectName(u"btnArt_culos")
        icon3 = QIcon()
        icon3.addFile(u":/Icons/PNG/articulos.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.btnArt_culos.setIcon(icon3)
        self.btnArt_culos.setIconVisibleInMenu(True)
        self.btnFormas_de_Pago = QAction(MainWindow)
        self.btnFormas_de_Pago.setObjectName(u"btnFormas_de_Pago")
        icon4 = QIcon()
        icon4.addFile(u":/Icons/PNG/Fp.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.btnFormas_de_Pago.setIcon(icon4)
        self.btnFormas_de_Pago.setIconVisibleInMenu(True)
        self.bttipos_de_Iva = QAction(MainWindow)
        self.bttipos_de_Iva.setObjectName(u"bttipos_de_Iva")
        icon5 = QIcon()
        icon5.addFile(u":/Icons/PNG/iva3.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bttipos_de_Iva.setIcon(icon5)
        self.bttipos_de_Iva.setIconVisibleInMenu(True)
        self.btnAgenda = QAction(MainWindow)
        self.btnAgenda.setObjectName(u"btnAgenda")
        icon6 = QIcon()
        icon6.addFile(u":/Icons/PNG/Calendar2.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnAgenda.setIcon(icon6)
        self.btnAgenda.setIconVisibleInMenu(True)
        self.btnSalir = QAction(MainWindow)
        self.btnSalir.setObjectName(u"btnSalir")
        icon7 = QIcon()
        icon7.addFile(u":/Icons/PNG/Exit.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnSalir.setIcon(icon7)
        self.btnSalir.setIconVisibleInMenu(True)
        self.actiopresupuestos = QAction(MainWindow)
        self.actiopresupuestos.setObjectName(u"actiopresupuestos")
        icon8 = QIcon()
        icon8.addFile(u":/Icons/PNG/presupuestos.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actiopresupuestos.setIcon(icon8)
        self.actiopresupuestos.setIconVisibleInMenu(True)
        self.actiopedidos = QAction(MainWindow)
        self.actiopedidos.setObjectName(u"actiopedidos")
        icon9 = QIcon()
        icon9.addFile(u":/Icons/PNG/pedidos_cli.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actiopedidos.setIcon(icon9)
        self.actiopedidos.setIconVisibleInMenu(True)
        self.actionFacturas = QAction(MainWindow)
        self.actionFacturas.setObjectName(u"actionFacturas")
        icon10 = QIcon()
        icon10.addFile(u":/Icons/PNG/Factura.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionFacturas.setIcon(icon10)
        self.actionFacturas.setIconVisibleInMenu(True)
        self.actionVentas_Contado = QAction(MainWindow)
        self.actionVentas_Contado.setObjectName(u"actionVentas_Contado")
        icon11 = QIcon()
        icon11.addFile(u":/Icons/PNG/tpv.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionVentas_Contado.setIcon(icon11)
        self.actionVentas_Contado.setIconVisibleInMenu(True)
        self.actionGestion_de_Secciones = QAction(MainWindow)
        self.actionGestion_de_Secciones.setObjectName(u"actionGestion_de_Secciones")
        self.actionGestion_de_Secciones.setIconVisibleInMenu(True)
        self.actionGestion_de_Familias = QAction(MainWindow)
        self.actionGestion_de_Familias.setObjectName(u"actionGestion_de_Familias")
        self.actionGestion_de_Familias.setIconVisibleInMenu(True)
        self.actionGestion_de_subfamilias = QAction(MainWindow)
        self.actionGestion_de_subfamilias.setObjectName(u"actionGestion_de_subfamilias")
        self.actionGestion_de_subfamilias.setIconVisibleInMenu(True)
        self.actionDoctores = QAction(MainWindow)
        self.actionDoctores.setObjectName(u"actionDoctores")
        self.actionDoctores.setIconVisibleInMenu(True)
        self.actionBancos = QAction(MainWindow)
        self.actionBancos.setObjectName(u"actionBancos")
        self.actionBancos.setIconVisibleInMenu(True)
        self.actionFormas_de_pago = QAction(MainWindow)
        self.actionFormas_de_pago.setObjectName(u"actionFormas_de_pago")
        self.actionTallas = QAction(MainWindow)
        self.actionTallas.setObjectName(u"actionTallas")
        self.actionConceptos_tallas = QAction(MainWindow)
        self.actionConceptos_tallas.setObjectName(u"actionConceptos_tallas")
        self.actionPaises = QAction(MainWindow)
        self.actionPaises.setObjectName(u"actionPaises")
        self.actionPaises.setIconVisibleInMenu(True)
        self.actionAvisos = QAction(MainWindow)
        self.actionAvisos.setObjectName(u"actionAvisos")
        self.actionAvisos.setIconVisibleInMenu(True)
        self.actiotipos_de_imagen = QAction(MainWindow)
        self.actiotipos_de_imagen.setObjectName(u"actiotipos_de_imagen")
        self.actiotipos_de_imagen.setIconVisibleInMenu(True)
        self.actiotipos_de_anal_tica = QAction(MainWindow)
        self.actiotipos_de_anal_tica.setObjectName(u"actiotipos_de_anal_tica")
        self.actiotipos_de_anal_tica.setIconVisibleInMenu(True)
        self.actionCampos_de_analitica = QAction(MainWindow)
        self.actionCampos_de_analitica.setObjectName(u"actionCampos_de_analitica")
        self.actionCampos_de_analitica.setIconVisibleInMenu(True)
        self.actionMotivos_de_interconsulta = QAction(MainWindow)
        self.actionMotivos_de_interconsulta.setObjectName(u"actionMotivos_de_interconsulta")
        self.actionMotivos_de_interconsulta.setIconVisibleInMenu(True)
        self.actiotipos_de_IVA = QAction(MainWindow)
        self.actiotipos_de_IVA.setObjectName(u"actiotipos_de_IVA")
        self.actionSubSubFamilias = QAction(MainWindow)
        self.actionSubSubFamilias.setObjectName(u"actionSubSubFamilias")
        self.actionSubSubFamilias.setIconVisibleInMenu(True)
        self.actionGrupos = QAction(MainWindow)
        self.actionGrupos.setObjectName(u"actionGrupos")
        self.actionGrupos.setIconVisibleInMenu(True)
        self.actionTarifas = QAction(MainWindow)
        self.actionTarifas.setObjectName(u"actionTarifas")
        self.actionTarifas.setIconVisibleInMenu(True)
        self.actioalbaranes_de_proveedores = QAction(MainWindow)
        self.actioalbaranes_de_proveedores.setObjectName(u"actioalbaranes_de_proveedores")
        self.actioalbaranes_de_proveedores.setIconVisibleInMenu(True)
        self.actionFacturas_de_proveedores_Acreedores = QAction(MainWindow)
        self.actionFacturas_de_proveedores_Acreedores.setObjectName(u"actionFacturas_de_proveedores_Acreedores")
        self.actionFacturas_de_proveedores_Acreedores.setIconVisibleInMenu(True)
        self.actioporc_recepci_n_de_Pedidos = QAction(MainWindow)
        self.actioporc_recepci_n_de_Pedidos.setObjectName(u"actioporc_recepci_n_de_Pedidos")
        self.actioporc_recepci_n_de_pedidos = QAction(MainWindow)
        self.actioporc_recepci_n_de_pedidos.setObjectName(u"actioporc_recepci_n_de_pedidos")
        self.actioporc_recepci_n_de_pedidos.setIconVisibleInMenu(True)
        self.actionGesti_n_de_devoluciones = QAction(MainWindow)
        self.actionGesti_n_de_devoluciones.setObjectName(u"actionGesti_n_de_devoluciones")
        self.actionGesti_n_de_devoluciones.setIconVisibleInMenu(True)
        self.actionRegularizaci_n_de_inventario = QAction(MainWindow)
        self.actionRegularizaci_n_de_inventario.setObjectName(u"actionRegularizaci_n_de_inventario")
        self.actionRegularizaci_n_de_inventario.setIconVisibleInMenu(True)
        self.actionGesti_n_de_Usuarios = QAction(MainWindow)
        self.actionGesti_n_de_Usuarios.setObjectName(u"actionGesti_n_de_Usuarios")
        self.actionGesti_n_de_Usuarios.setIconVisibleInMenu(True)
        self.actionPermisos = QAction(MainWindow)
        self.actionPermisos.setObjectName(u"actionPermisos")
        self.actionPermisos.setIconVisibleInMenu(True)
        self.actionEmisi_n_de_recetas_a_pacientes = QAction(MainWindow)
        self.actionEmisi_n_de_recetas_a_pacientes.setObjectName(u"actionEmisi_n_de_recetas_a_pacientes")
        self.actionEmisi_n_de_recetas_a_pacientes.setIconVisibleInMenu(True)
        self.actionCertificados = QAction(MainWindow)
        self.actionCertificados.setObjectName(u"actionCertificados")
        self.actionCertificados.setIconVisibleInMenu(True)
        self.actionGesti_n_de_comisiones = QAction(MainWindow)
        self.actionGesti_n_de_comisiones.setObjectName(u"actionGesti_n_de_comisiones")
        self.actionGesti_n_de_comisiones.setIconVisibleInMenu(True)
        self.actiotipos_de_paciente = QAction(MainWindow)
        self.actiotipos_de_paciente.setObjectName(u"actiotipos_de_paciente")
        self.actiotipos_de_paciente.setIconVisibleInMenu(True)
        self.actionTraspasos_entre_almacenes = QAction(MainWindow)
        self.actionTraspasos_entre_almacenes.setObjectName(u"actionTraspasos_entre_almacenes")
        self.actionTraspasos_entre_almacenes.setIconVisibleInMenu(True)
        self.actionGesti_n_de_Pagos = QAction(MainWindow)
        self.actionGesti_n_de_Pagos.setObjectName(u"actionGesti_n_de_Pagos")
        self.actionGesti_n_de_Pagos.setIconVisibleInMenu(True)
        self.actionFacturaci_n_multiple_de_albaranes = QAction(MainWindow)
        self.actionFacturaci_n_multiple_de_albaranes.setObjectName(u"actionFacturaci_n_multiple_de_albaranes")
        self.actionFacturaci_n_multiple_de_albaranes.setIconVisibleInMenu(True)
        self.actioalbaranes_2 = QAction(MainWindow)
        self.actioalbaranes_2.setObjectName(u"actioalbaranes_2")
        self.actioalbaranes_2.setIconVisibleInMenu(True)
        self.actionEdici_n_de_Reports = QAction(MainWindow)
        self.actionEdici_n_de_Reports.setObjectName(u"actionEdici_n_de_Reports")
        self.actionEdici_n_de_Reports.setIconVisibleInMenu(True)
        self.actionOrdenes_de_pedidos = QAction(MainWindow)
        self.actionOrdenes_de_pedidos.setObjectName(u"actionOrdenes_de_pedidos")
        self.actionOrdenes_de_pedidos.setIconVisibleInMenu(True)
        self.actionCompras_por_producto = QAction(MainWindow)
        self.actionCompras_por_producto.setObjectName(u"actionCompras_por_producto")
        self.actionCompras_por_producto.setIconVisibleInMenu(True)
        self.actionCompras_por_proveedor = QAction(MainWindow)
        self.actionCompras_por_proveedor.setObjectName(u"actionCompras_por_proveedor")
        self.actionCompras_por_proveedor.setIconVisibleInMenu(True)
        self.actionPor_proveedor = QAction(MainWindow)
        self.actionPor_proveedor.setObjectName(u"actionPor_proveedor")
        self.actionPor_proveedor.setIconVisibleInMenu(True)
        self.actionPor_fecha = QAction(MainWindow)
        self.actionPor_fecha.setObjectName(u"actionPor_fecha")
        self.actionPor_fecha.setIconVisibleInMenu(True)
        self.actionPor_producto = QAction(MainWindow)
        self.actionPor_producto.setObjectName(u"actionPor_producto")
        self.actionPor_proveedor_2 = QAction(MainWindow)
        self.actionPor_proveedor_2.setObjectName(u"actionPor_proveedor_2")
        self.actionPor_proveedor_2.setIconVisibleInMenu(True)
        self.actionPor_fecha_2 = QAction(MainWindow)
        self.actionPor_fecha_2.setObjectName(u"actionPor_fecha_2")
        self.actionPor_fecha_2.setIconVisibleInMenu(True)
        self.actionPendientes = QAction(MainWindow)
        self.actionPendientes.setObjectName(u"actionPendientes")
        self.actionPendientes.setIconVisibleInMenu(True)
        self.actionCompletos = QAction(MainWindow)
        self.actionCompletos.setObjectName(u"actionCompletos")
        self.actionCompletos.setIconVisibleInMenu(True)
        self.actionPor_Proveedor = QAction(MainWindow)
        self.actionPor_Proveedor.setObjectName(u"actionPor_Proveedor")
        self.actionPor_Proveedor.setIconVisibleInMenu(True)
        self.actionPor_fecha_3 = QAction(MainWindow)
        self.actionPor_fecha_3.setObjectName(u"actionPor_fecha_3")
        self.actionPor_fecha_3.setIconVisibleInMenu(True)
        self.actionPor_Proveedor_2 = QAction(MainWindow)
        self.actionPor_Proveedor_2.setObjectName(u"actionPor_Proveedor_2")
        self.actionPor_Proveedor_2.setIconVisibleInMenu(True)
        self.actionPor_Fecha = QAction(MainWindow)
        self.actionPor_Fecha.setObjectName(u"actionPor_Fecha")
        self.actionPor_Fecha.setIconVisibleInMenu(True)
        self.actionPendientes_de_pago = QAction(MainWindow)
        self.actionPendientes_de_pago.setObjectName(u"actionPendientes_de_pago")
        self.actionPendientes_de_pago.setIconVisibleInMenu(True)
        self.actionPor_grupos_de_gasto = QAction(MainWindow)
        self.actionPor_grupos_de_gasto.setObjectName(u"actionPor_grupos_de_gasto")
        self.actionPor_grupos_de_gasto.setIconVisibleInMenu(True)
        self.actionPermisos_de_Agenda = QAction(MainWindow)
        self.actionPermisos_de_Agenda.setObjectName(u"actionPermisos_de_Agenda")
        self.actionMonedas = QAction(MainWindow)
        self.actionMonedas.setObjectName(u"actionMonedas")
        self.actionGestion_Pedidos_Pro = QAction(MainWindow)
        self.actionGestion_Pedidos_Pro.setObjectName(u"actionGestion_Pedidos_Pro")
        icon12 = QIcon()
        icon12.addFile(u":/Icons/PNG/pedido_pro.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionGestion_Pedidos_Pro.setIcon(icon12)
        self.actioporc_recepcion_de_pedido_pro = QAction(MainWindow)
        self.actioporc_recepcion_de_pedido_pro.setObjectName(u"actioporc_recepcion_de_pedido_pro")
        icon13 = QIcon()
        icon13.addFile(u":/Icons/PNG/recepcion_ped.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actioporc_recepcion_de_pedido_pro.setIcon(icon13)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(18, -1, -1, -1)
        self.frameusuario = QFrame(self.centralwidget)
        self.frameusuario.setObjectName(u"frameusuario")
        self.frameusuario.setMinimumSize(QSize(0, 38))
        self.frameusuario.setMaximumSize(QSize(16777215, 38))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush)
# self.frameusuario.setPalette(palette)
        self.frameusuario.setStyleSheet(u"\n"
"background-color: rgb(0,0,0);")
        self.frameusuario.setFrameShape(QFrame.Shape.StyledPanel)
        self.frameusuario.setFrameShadow(QFrame.Shadow.Plain)
        self.horizontalLayout = QHBoxLayout(self.frameusuario)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(9, 1, 9, 1)
        self.label_5 = QLabel(self.frameusuario)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setMaximumSize(QSize(32, 32))
        self.label_5.setPixmap(QPixmap(u"PNG/Logoimage.png"))
        self.label_5.setScaledContents(True)

        self.horizontalLayout.addWidget(self.label_5)

        self.img_avisos = QLabel(self.frameusuario)
        self.img_avisos.setObjectName(u"img_avisos")
        self.img_avisos.setMaximumSize(QSize(40, 16777215))
        self.img_avisos.setPixmap(QPixmap(u":/Icons/PNG/Mail.png"))
        self.img_avisos.setScaledContents(True)

        self.horizontalLayout.addWidget(self.img_avisos)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_2)

        self.shortCutContainer = QHBoxLayout()
        self.shortCutContainer.setObjectName(u"shortCutContainer")

        self.horizontalLayout.addLayout(self.shortCutContainer)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.label = QLabel(self.frameusuario)
        self.label.setObjectName(u"label")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy1)
        palette1 = QPalette()
        brush1 = QBrush(QColor(255, 255, 127, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush)
        brush2 = QBrush(QColor(255, 255, 127, 128))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush2)
#endif
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush2)
#endif
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush2)
#endif
# self.label.setPalette(palette1)
        self.label.setStyleSheet(u"font: 75 10pt \"Cantarell\";\n"
"color: rgb(255, 255, 127);")

        self.gridLayout.addWidget(self.label, 0, 0, 3, 1)

        self.btn_salir = QPushButton(self.frameusuario)
        self.btn_salir.setObjectName(u"btn_salir")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.btn_salir.sizePolicy().hasHeightForWidth())
        self.btn_salir.setSizePolicy(sizePolicy2)
        self.btn_salir.setAutoFillBackground(False)
        self.btn_salir.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(133, 170, 142);")
        self.btn_salir.setIcon(icon7)
        self.btn_salir.setIconSize(QSize(26, 26))
        self.btn_salir.setFlat(False)

        self.gridLayout.addWidget(self.btn_salir, 0, 4, 3, 1)

        self.btn_bloquear = QPushButton(self.frameusuario)
        self.btn_bloquear.setObjectName(u"btn_bloquear")
        sizePolicy2.setHeightForWidth(self.btn_bloquear.sizePolicy().hasHeightForWidth())
        self.btn_bloquear.setSizePolicy(sizePolicy2)
        self.btn_bloquear.setMinimumSize(QSize(0, 27))
        self.btn_bloquear.setAutoFillBackground(False)
        self.btn_bloquear.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(133, 170, 142);")
        icon14 = QIcon()
        icon14.addFile(u":/Icons/PNG/cierecaja.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_bloquear.setIcon(icon14)
        self.btn_bloquear.setIconSize(QSize(26, 26))

        self.gridLayout.addWidget(self.btn_bloquear, 0, 3, 3, 1)

        self.lineUsuarioActivo = QPushButton(self.frameusuario)
        self.lineUsuarioActivo.setObjectName(u"lineUsuarioActivo")
        self.lineUsuarioActivo.setStyleSheet(u"font: 75 10pt \"Cantarell\";\n"
"color: rgb(255, 255, 127);")
        self.lineUsuarioActivo.setFlat(True)

        self.gridLayout.addWidget(self.lineUsuarioActivo, 0, 1, 3, 1)

        self.txtEjercicio = QDateEdit(self.frameusuario)
        self.txtEjercicio.setObjectName(u"txtEjercicio")
        self.txtEjercicio.setStyleSheet(u"color: rgb(255, 255, 127);")
        self.txtEjercicio.setDateTime(QDateTime(QDate(2025, 1, 1), QTime(0, 0, 0)))
        self.txtEjercicio.setDate(QDate(2025, 1, 1))

        self.gridLayout.addWidget(self.txtEjercicio, 0, 2, 3, 1)


        self.horizontalLayout.addLayout(self.gridLayout)


        self.verticalLayout.addWidget(self.frameusuario)

        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet(u"")

        self.verticalLayout.addWidget(self.stackedWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1245, 30))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menuArchivos = QMenu(self.menubar)
        self.menuArchivos.setObjectName(u"menuArchivos")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuArchivos.menuAction())

        self.retranslateUi(MainWindow)
        self.btn_salir.clicked.connect(MainWindow.close)

        self.stackedWidget.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MAYA - ERP/GNU para los profesionales de la Salud", None))
        self.btnClientes.setText(QCoreApplication.translate("MainWindow", u"Gesti\u00f3n de Pacientes", None))
        self.btnProveedores.setText(QCoreApplication.translate("MainWindow", u"Gesti\u00f3n de Proveedores", None))
        self.btnArt_culos.setText(QCoreApplication.translate("MainWindow", u"Gesti\u00f3n de Art\u00edculos", None))
        self.btnFormas_de_Pago.setText(QCoreApplication.translate("MainWindow", u"Gesti\u00f3n de Formas de Pago", None))
        self.bttipos_de_Iva.setText(QCoreApplication.translate("MainWindow", u"Gesti\u00f3n de Tipos de Iva", None))
        self.btnAgenda.setText(QCoreApplication.translate("MainWindow", u"Gesti\u00f3n de la Agenda", None))
        self.btnSalir.setText(QCoreApplication.translate("MainWindow", u"Salir de Maya", None))
        self.actiopresupuestos.setText(QCoreApplication.translate("MainWindow", u"Presupuestos", None))
        self.actiopedidos.setText(QCoreApplication.translate("MainWindow", u"Pedidos", None))
        self.actionFacturas.setText(QCoreApplication.translate("MainWindow", u"Facturas", None))
        self.actionVentas_Contado.setText(QCoreApplication.translate("MainWindow", u"Ventas Contado", None))
        self.actionGestion_de_Secciones.setText(QCoreApplication.translate("MainWindow", u"Secciones", None))
        self.actionGestion_de_Familias.setText(QCoreApplication.translate("MainWindow", u"Familias", None))
        self.actionGestion_de_subfamilias.setText(QCoreApplication.translate("MainWindow", u"SubFamilias", None))
        self.actionDoctores.setText(QCoreApplication.translate("MainWindow", u"Doctores", None))
        self.actionBancos.setText(QCoreApplication.translate("MainWindow", u"Bancos", None))
        self.actionFormas_de_pago.setText(QCoreApplication.translate("MainWindow", u"Formas de pago", None))
        self.actionTallas.setText(QCoreApplication.translate("MainWindow", u"Tallas", None))
        self.actionConceptos_tallas.setText(QCoreApplication.translate("MainWindow", u"Conceptos tallas", None))
        self.actionPaises.setText(QCoreApplication.translate("MainWindow", u"Paises", None))
        self.actionAvisos.setText(QCoreApplication.translate("MainWindow", u"Avisos", None))
        self.actiotipos_de_imagen.setText(QCoreApplication.translate("MainWindow", u"Tipos de imagen", None))
        self.actiotipos_de_anal_tica.setText(QCoreApplication.translate("MainWindow", u"Tipos de anal\u00edtica", None))
        self.actionCampos_de_analitica.setText(QCoreApplication.translate("MainWindow", u"Campos de analitica", None))
        self.actionMotivos_de_interconsulta.setText(QCoreApplication.translate("MainWindow", u"Motivos de interconsulta", None))
        self.actiotipos_de_IVA.setText(QCoreApplication.translate("MainWindow", u"Tipos de I.V.A", None))
        self.actionSubSubFamilias.setText(QCoreApplication.translate("MainWindow", u"SubSubFamilias", None))
        self.actionGrupos.setText(QCoreApplication.translate("MainWindow", u"Grupos", None))
        self.actionTarifas.setText(QCoreApplication.translate("MainWindow", u"Tipos de Tarifa", None))
        self.actioalbaranes_de_proveedores.setText(QCoreApplication.translate("MainWindow", u"Albaranes de proveedores", None))
        self.actionFacturas_de_proveedores_Acreedores.setText(QCoreApplication.translate("MainWindow", u"Facturas de proveedores/Acreedores", None))
        self.actioporc_recepci_n_de_Pedidos.setText(QCoreApplication.translate("MainWindow", u"Recepci\u00f3n de Pedidos", None))
        self.actioporc_recepci_n_de_pedidos.setText(QCoreApplication.translate("MainWindow", u"Recepci\u00f3n  de pedidos", None))
        self.actionGesti_n_de_devoluciones.setText(QCoreApplication.translate("MainWindow", u"Gesti\u00f3n de devoluciones", None))
        self.actionRegularizaci_n_de_inventario.setText(QCoreApplication.translate("MainWindow", u"Regularizaci\u00f3n de inventario", None))
        self.actionGesti_n_de_Usuarios.setText(QCoreApplication.translate("MainWindow", u"Gesti\u00f3n de Usuarios", None))
        self.actionPermisos.setText(QCoreApplication.translate("MainWindow", u"Permisos", None))
        self.actionEmisi_n_de_recetas_a_pacientes.setText(QCoreApplication.translate("MainWindow", u"Emisi\u00f3n de recetas a pacientes", None))
        self.actionCertificados.setText(QCoreApplication.translate("MainWindow", u"Certificados", None))
        self.actionGesti_n_de_comisiones.setText(QCoreApplication.translate("MainWindow", u"Gesti\u00f3n de comisiones", None))
        self.actiotipos_de_paciente.setText(QCoreApplication.translate("MainWindow", u"Tipos de paciente", None))
        self.actionTraspasos_entre_almacenes.setText(QCoreApplication.translate("MainWindow", u"Traspasos entre almacenes", None))
        self.actionGesti_n_de_Pagos.setText(QCoreApplication.translate("MainWindow", u"Gesti\u00f3n de Pagos", None))
        self.actionFacturaci_n_multiple_de_albaranes.setText(QCoreApplication.translate("MainWindow", u"Facturaci\u00f3n multiple de albaranes", None))
        self.actioalbaranes_2.setText(QCoreApplication.translate("MainWindow", u"Albaranes", None))
        self.actionEdici_n_de_Reports.setText(QCoreApplication.translate("MainWindow", u"Edici\u00f3n de 'Reports'", None))
        self.actionOrdenes_de_pedidos.setText(QCoreApplication.translate("MainWindow", u"Ordenes de pedidos", None))
        self.actionCompras_por_producto.setText(QCoreApplication.translate("MainWindow", u"compras por producto", None))
        self.actionCompras_por_proveedor.setText(QCoreApplication.translate("MainWindow", u"Compras por proveedor", None))
        self.actionPor_proveedor.setText(QCoreApplication.translate("MainWindow", u"por proveedor", None))
        self.actionPor_fecha.setText(QCoreApplication.translate("MainWindow", u"por fecha", None))
        self.actionPor_producto.setText(QCoreApplication.translate("MainWindow", u"por producto", None))
        self.actionPor_proveedor_2.setText(QCoreApplication.translate("MainWindow", u"Por proveedor", None))
        self.actionPor_fecha_2.setText(QCoreApplication.translate("MainWindow", u"Por fecha", None))
        self.actionPendientes.setText(QCoreApplication.translate("MainWindow", u"Pendientes", None))
        self.actionCompletos.setText(QCoreApplication.translate("MainWindow", u"Completos", None))
        self.actionPor_Proveedor.setText(QCoreApplication.translate("MainWindow", u"Por Proveedor", None))
        self.actionPor_fecha_3.setText(QCoreApplication.translate("MainWindow", u"Por fecha", None))
        self.actionPor_Proveedor_2.setText(QCoreApplication.translate("MainWindow", u"Por Proveedor", None))
        self.actionPor_Fecha.setText(QCoreApplication.translate("MainWindow", u"Por Fecha", None))
        self.actionPendientes_de_pago.setText(QCoreApplication.translate("MainWindow", u"Pendientes de pago", None))
        self.actionPor_grupos_de_gasto.setText(QCoreApplication.translate("MainWindow", u"Por grupos de gasto", None))
        self.actionPermisos_de_Agenda.setText(QCoreApplication.translate("MainWindow", u"Permisos de Agenda", None))
        self.actionMonedas.setText(QCoreApplication.translate("MainWindow", u"Monedas", None))
        self.actionGestion_Pedidos_Pro.setText(QCoreApplication.translate("MainWindow", u"Gesti\u00f3n de Pedidos", None))
        self.actioporc_recepcion_de_pedido_pro.setText(QCoreApplication.translate("MainWindow", u"Recepci\u00f3n de pedido", None))
        self.label_5.setText("")
        self.img_avisos.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Usuario:", None))
#if QT_CONFIG(tooltip)
        self.btn_salir.setToolTip(QCoreApplication.translate("MainWindow", u"Salir de Maya", None))
#endif // QT_CONFIG(tooltip)
        self.btn_salir.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
#if QT_CONFIG(tooltip)
        self.btn_bloquear.setToolTip(QCoreApplication.translate("MainWindow", u"Bloquear Maya", None))
#endif // QT_CONFIG(tooltip)
        self.btn_bloquear.setText(QCoreApplication.translate("MainWindow", u"Bloq.", None))
        self.lineUsuarioActivo.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.txtEjercicio.setDisplayFormat(QCoreApplication.translate("MainWindow", u"yyyy", None))
        self.menuArchivos.setTitle(QCoreApplication.translate("MainWindow", u"Archivos", None))
    # retranslateUi

